[package]
name = "modo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.0"
regex = "1"
tempdir = "0.3"
anyhow = "1.0.56"
clap = { version = "3.1.6", features = ["derive"] }